# 29/04/2025

# Each new term in the Fibonacci sequence is generated by adding
# the previous two terms.

# By starting with 1 and 2, the first 10 terms will be:

example = [1, 2, 3, 5, 8, 13, 21, "etc"]

# By considering the terms in the Fibonaci sequence whose values do not
# exceed four million, find the sum of the even-valued terms.

def func():

    fib = [1, 2] # stores Fibonacci

    result = 2 # sum of even-valued terms

    while fib[-1] < 4000000: # while last fib number in sequence < 4m
        fib.append((fib[-1] + fib[-2])) # appending next fib number to sequence
        if fib[-1] % 2 == 0: # if even:
            result += fib[-1] # adding to result
        else:
            continue
    
    return result 

print(func()) # Prints correct result: 4613732

# 818080th person to have solved this problem.